### PR TITLE
fix: expose simplicial cholesky on sparse matrices

### PR DESCRIPTION
**Pull request by Bangybug**
Hi, Could you please advise how do I properly expose SimplicialCholesky from libeigen to js? 

Thank you

### CODE REVIEW

**Comment by BertrandBev** [comment]
@Bangybug did you test these changes?

**Comment by Bangybug** [comment]
@BertrandBev I'm making a comparison test in C++ and JS, it takes some time.  I will upload the test here and let you know.

**Comment by Bangybug** [comment]
@BertrandBev I made a test, it has two parts:
- src/tests/cpp/simplicialcholesky/Tutorial_sparse_example.cpp -- taken from libeigen
- src/tests/ts/simplicialcholesky/Tutorial_sparse_example.ts -- ported to Typescript
I'm satisfied with the results, they are in perfect match and time profile is good.

However I have some issues with the actual organization of the test code, they are listed in /src/tests/readme.md

**Comment by BertrandBev** [comment]
Thanks @Bangybug for the good addition! I'll take time to add it to the interactive documentation at some point

**Pull request merged**
